const data = {
  products: [
    {
      name: "Mantra M1",
      slug: "mantra-guitar",
      category: "Music",
      image: "/images/mantra.jpg",
      price: 217,
      countInStock: 10,
      brand: "Mantra",
      rating: 4.5,
      numReviews: 10,
      description: "Good One",
    },
    {
      name: "Signature M1",
      slug: "signature-guitar",
      category: "Music",
      image: "/images/signature.jpg",
      price: 217,
      countInStock: 10,
      brand: "Signature",
      rating: 4.5,
      numReviews: 10,
      description: "Good One",
    },
    {
      name: "Yamaha M1",
      slug: "yamaha-guitar",
      category: "Music",
      image: "/images/yamaha.jpg",
      price: 217,
      countInStock: 10,
      brand: "Yamaha",
      rating: 4.5,
      numReviews: 10,
      description: "Good One",
    },
    {
      name: "Electric Guitar",
      slug: "electric-guitar",
      category: "Music",
      image: "/images/eletric.jpg",
      price: 217,
      countInStock: 10,
      brand: "Yamaha",
      rating: 4.5,
      numReviews: 10,
      description: "Good One",
    },
  ],
};

export default data;
